# MPV configuration file

## For Auto HW Decoding
## Crashing if any NVIDIA HW is installed https://github.com/mpv-player/mpv/issues/17688
#hwdec=auto

## For Vulkan HW Decoding
## https://github.com/mpv-player/mpv/discussions/13909
## As long as [VK_KHR_video_decode_av1](https://docs.vulkan.org/features/latest/features/proposals/VK_KHR_video_decode_av1.html)
## is missing from the `vulkaninfo` output, AV1 decoding won't be available on the hardware.
# vo=gpu-next
# gpu-api=vulkan
# hwdec=vulkan
## The gpu-context is usually by default on waylandvk anyway with the above 3 flags and running on wayland
##gpu-context=waylandvk
## Check available Vulkan devices with
## /app/bin/mpv --vulkan-device=help
##vulkan-device='Quadro T1000'

## For CUDA (NVENC/NVDEC) HW Decoding
## https://trac.ffmpeg.org/wiki/HWAccelIntro#CUDANVENCNVDEC
## "NVENC and NVDEC are NVIDIA's hardware-accelerated encoding and decoding APIs. They used to be called CUVID."
## "hardware decoders rarely implement all of them (for example, hardware decoders tend not to implement anything beyond YUV 4:2:0 at 8-bit depth for H.264)."
## While `av1_cuvid` is available even for older hardware, it still doesn't support YouTube's AV1 Chroma somehow:
## `[ffmpeg/video] av1_cuvid: Codec av1_cuvid is not supported with this chroma format.`
## Check if CUVID is even available
## /app/bin/mpv --vd=help
## https://github.com/mpv-player/mpv/discussions/17146
# vo=gpu-next
# gpu-api=vulkan
# # Alternatively opengl also works here
# #gpu-api=opengl
# hwdec=cuda-copy
# #vd=av1_cuvid
# #vd=vp9_cuvid

## For VAAPI HW Decoding
## https://trac.ffmpeg.org/wiki/HWAccelIntro#VAAPI
## Currently appears to be broken on nvidia laptops with external monitors.
# vo=vaapi
# gpu-api=vulkan
# hwdec=vaapi
# gpu-context=waylandvk


# Customize logging here.
# If you need more modules, then start with `all=v` and find the right module
#msg-level=all=v
# If level `v` is not enough, then increase with `debug` or `trace`
msg-level=vd=v,ad=v,vo=v

# List the available properties with `mpv --list-properties`
term-playing-msg='Video Codec: ${video-codec}, Audio Codec: ${audio-codec}'

# On HW, where AV1 HW decoding is not available, request VP9 insteadon higher than 1440p  quality.
# As seen on https://github.com/mpv-player/mpv/discussions/14469#discussioncomment-9920230
ytdl-format=bestvideo[height>=?1440][vcodec^=vp9]+bestaudio/bestvideo[height<=?1440][vcodec^=av0]+bestaudio/bestvideo+bestaudio/best
