wtf:
  colors:
    background: black
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
    checked: yellow
    highlight: 
      fore: black
      back: gray
    rows:
      even: yellow
      odd: white
  grid:
    # How _wide_ the columns are, in terminal characters. In this case we have
    # five columns, four of which are 35 characters wide, and one is 60.
    columns: [140]
    # How _high_ the rows are, in terminal lines. In this case we have four rows
    # that support ten line of text and one of four.
    rows: [40, 40]
  refreshInterval: 1
  openFileUtil: "open"
  mods:
    prettyweather_1:
      type: prettyweather
      enabled: true
      city: "Budapest"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 300
      unit: "c"
      view: n
      language: "en"
    prettyweather_2:
      type: prettyweather
      enabled: true
      city: "Pewsum"
      position:
        top: 1
        left: 0
        height: 1
        width: 1
      refreshInterval: 300
      unit: "c"
      view: 0
      language: "de"
