wtf:
  colors:
    background: black
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
    checked: yellow
    highlight:
      fore: black
      back: gray
    rows:
      even: yellow
      odd: white
  grid:
    # How _wide_ the columns are, in terminal characters. In this case we have
    # five columns, four of which are 35 characters wide, and one is 60.
    columns: [35, 35, 35, 35, 60]
    # How _high_ the rows are, in terminal lines. In this case we have four rows
    # that support ten line of text and one of four.
    rows: [11, 10, 10, 10, 4, 30]
  refreshInterval: 1
  openFileUtil: "open"
  mods:
    # You can have multiple widgets of the same type.
    # The "key" is the name of the widget and the type is the actual
    # widget you want to implement.
    relevant_timezones:
      title: "🕐 Time"
      type: clocks
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        # From https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        Atlanta: "America/New_York"
        Austin: "America/Chicago"
        Boston: "America/New_York"
        Cork: "Europe/Dublin"
        Ehningen: "Europe/Berlin"
        Kochi: "Asia/Kolkata"
        Markham: "America/Toronto"
        San_Jose: "America/Los_Angeles"
        GMT: "Etc/GMT"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: "reversechronological"
    jira_board:
      type: cmdrunner
      title: "🔷 Jira"
      cmd: "jiraScript.sh"
      enabled: true
      refreshInterval: 15m
      position:
        top: 0
        left: 1
        height: 1
        width: 3
    battery:
      type: power
      title: "⚡️ 🔋"
      enabled: true
      position:
        top: 1
        left: 3
        height: 1
        width: 1
      refreshInterval: 15
    todolist:
      type: todo
      checkedIcon: "X"
      colors:
        checked: gray
        highlight:
          fore: "black"
          back: "orange"
      enabled: true
      filename: "todo.yml"
      position:
        top: 1
        left: 0
        height: 2
        width: 1
    refreshInterval: 3600
    ip:
      type: ipinfo
      title: "🌐 IP"
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 2
        left: 3
        height: 1
        width: 1
      refreshInterval: 150
    security_info:
      type: security
      title: "🛡️ Firewall & Network security"
      enabled: true
      colors:
        subheading: darkgreen
      position:
        top: 1
        left: 2
        height: 2
        width: 1
      refreshInterval: 3600
  # readme:
  #   type: textfile
  #   enabled: true
  #   filePaths:
  #     - "~/.config/wtf/config.yml"
  #   format: true
  #   formatStyle: "monokai"
  #   position:
  #     top: 1
  #     left: 1
  #     height: 1
  #     width: 1
  #   refreshInterval: 15
    resources:
      type: resourceusage
      enabled: true
      position:
        top: 3
        left: 0
        height: 2
        width: 1
      refreshInterval: 1
    uptime:
      title: "⬆️ Updates"
      type: cmdrunner
      cmd: "checkVersions.sh"
      enabled: true
      position:
        top: 4
        left: 1
        height: 2
        width: 3
      refreshInterval: 1h
    disks:
      title: "📂 💽"
      type: cmdrunner
      cmd: "sdf"
      #args: ["-h"]
      enabled: true
      position:
        top: 3
        left: 1
        height: 1
        width: 1
      refreshInterval: 3600
